//+------------------------------------------------------------------+
//| MultiAlpha_Builder_FreeSlot_Panel_v1_09.mqh                     |
//| Scrollable variable-length free-slot board. UI only / NO ORDERS. |
//+------------------------------------------------------------------+
#ifndef MULTIALPHA_BUILDER_FREE_SLOT_PANEL_V1_09_MQH
#define MULTIALPHA_BUILDER_FREE_SLOT_PANEL_V1_09_MQH
#define MA_BUILDER_FREE_SLOT_PANEL_VERSION "1.09"
#define MA_BUILDER_INITIAL_SLOTS 8
#define MA_BUILDER_VISIBLE_ROWS 8
#define MA_BUILDER_MAX_UI_SLOTS 64
class CMultiAlphaBuilderFreeSlotPanel109{
 string p,slot[MA_BUILDER_MAX_UI_SLOTS],params[MA_BUILDER_MAX_UI_SLOTS]; int selected,slot_count,scroll;
 void Lab(string id,int x,int y,string s,int fs=8){string n=p+id;if(ObjectFind(0,n)<0)ObjectCreate(0,n,OBJ_LABEL,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(0,n,OBJPROP_COLOR,clrWhite);ObjectSetInteger(0,n,OBJPROP_FONTSIZE,fs);ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false);ObjectSetInteger(0,n,OBJPROP_ZORDER,35);ObjectSetString(0,n,OBJPROP_TEXT,s);}
 void Btn(string id,int x,int y,int w,string s,int state=0){string n=p+id;if(ObjectFind(0,n)<0)ObjectCreate(0,n,OBJ_BUTTON,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(0,n,OBJPROP_XSIZE,w);ObjectSetInteger(0,n,OBJPROP_YSIZE,22);color bg=(state==2?C'32,135,160':(state==1?C'30,82,98':C'24,39,49'));ObjectSetInteger(0,n,OBJPROP_BGCOLOR,bg);ObjectSetInteger(0,n,OBJPROP_COLOR,clrWhite);ObjectSetInteger(0,n,OBJPROP_FONTSIZE,8);ObjectSetInteger(0,n,OBJPROP_ZORDER,40);ObjectSetString(0,n,OBJPROP_TEXT,s);}
 void Edit(string id,int x,int y,int w,string s){string n=p+id;if(ObjectFind(0,n)<0)ObjectCreate(0,n,OBJ_EDIT,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(0,n,OBJPROP_XSIZE,w);ObjectSetInteger(0,n,OBJPROP_YSIZE,22);ObjectSetInteger(0,n,OBJPROP_BGCOLOR,C'20,31,40');ObjectSetInteger(0,n,OBJPROP_COLOR,clrWhite);ObjectSetInteger(0,n,OBJPROP_BORDER_COLOR,C'65,90,105');ObjectSetInteger(0,n,OBJPROP_FONTSIZE,8);ObjectSetInteger(0,n,OBJPROP_ZORDER,45);ObjectSetString(0,n,OBJPROP_TEXT,s);}
 void Box(){string n=p+"BG";if(ObjectFind(0,n)<0)ObjectCreate(0,n,OBJ_RECTANGLE_LABEL,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,640);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,58);ObjectSetInteger(0,n,OBJPROP_XSIZE,660);ObjectSetInteger(0,n,OBJPROP_YSIZE,470);ObjectSetInteger(0,n,OBJPROP_BGCOLOR,C'12,20,27');ObjectSetInteger(0,n,OBJPROP_BORDER_COLOR,C'55,70,80');ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false);ObjectSetInteger(0,n,OBJPROP_ZORDER,20);}
 int Row(string s){for(int r=0;r<MA_BUILDER_VISIBLE_ROWS;r++)if(s==p+"S"+IntegerToString(r)||s==p+"E"+IntegerToString(r))return r;return -1;}
 string Name(){string n=p+"NAME";return ObjectFind(0,n)>=0?ObjectGetString(0,n,OBJPROP_TEXT):"BUILDER_E01";}
 void Clamp(){int mx=MathMax(0,slot_count-MA_BUILDER_VISIBLE_ROWS);if(scroll<0)scroll=0;if(scroll>mx)scroll=mx;}
public:
 CMultiAlphaBuilderFreeSlotPanel109(){p="MAFREESLOT109_";selected=-1;slot_count=MA_BUILDER_INITIAL_SLOTS;scroll=0;for(int i=0;i<MA_BUILDER_MAX_UI_SLOTS;i++){slot[i]="EMPTY";params[i]="";}}
 int Selected(){return selected;} int SlotCount(){return slot_count;} string SelectedPart(){return selected>=0&&selected<slot_count?slot[selected]:"NONE";} string SelectedParams(){return selected>=0&&selected<slot_count?params[selected]:"";}
 void Export(string &a[],string &v[]){ArrayResize(a,slot_count);ArrayResize(v,slot_count);for(int i=0;i<slot_count;i++){a[i]=slot[i];v[i]=params[i];}}
 bool PutSelected(string part,string par){if(selected<0||selected>=slot_count)return false;slot[selected]=part;params[selected]=par;return true;}
 bool DeleteSelected(){if(selected<0||selected>=slot_count)return false;slot[selected]="EMPTY";params[selected]="";return true;}
 void ClearSlots(){for(int i=0;i<MA_BUILDER_MAX_UI_SLOTS;i++){slot[i]="EMPTY";params[i]="";}selected=-1;slot_count=MA_BUILDER_INITIAL_SLOTS;scroll=0;}
 void LoadO01EntryExample(){ClearSlots();string a[8]={"CYCLE_NEW","AND","TIME_ALLOWED","AND","FILTERS_OK","AND","RSI_THRESHOLD","SIGNAL BUY/SELL"};for(int i=0;i<8;i++)slot[i]=a[i];params[6]="TF=CURRENT;PERIOD=8;PRICE=CLOSE;COND=LT;LEVEL=30";selected=-1;}
 bool SaveNamed(string &reason){string nm=Name();if(nm==""){reason="NAME REQUIRED";return false;}string fn="MultiAlpha_Builder_"+nm+".csv";int h=FileOpen(fn,FILE_WRITE|FILE_CSV|FILE_COMMON,'|');if(h==INVALID_HANDLE){reason="FILE OPEN";return false;}FileWrite(h,"MA_BUILDER","1.09",slot_count);for(int i=0;i<slot_count;i++)FileWrite(h,i+1,slot[i],params[i]);FileClose(h);reason="SAVED: "+nm;return true;}
 bool LoadNamed(string &reason){string nm=Name();if(nm==""){reason="NAME REQUIRED";return false;}string fn="MultiAlpha_Builder_"+nm+".csv";int h=FileOpen(fn,FILE_READ|FILE_CSV|FILE_COMMON,'|');if(h==INVALID_HANDLE){reason="NOT FOUND: "+nm;return false;}string sig=FileReadString(h),ver=FileReadString(h);int n=(int)FileReadNumber(h);if(sig!="MA_BUILDER"||n<1||n>MA_BUILDER_MAX_UI_SLOTS){FileClose(h);reason="INVALID FILE";return false;}for(int i=0;i<MA_BUILDER_MAX_UI_SLOTS;i++){slot[i]="EMPTY";params[i]="";}slot_count=MathMax(MA_BUILDER_INITIAL_SLOTS,n);for(int i=0;i<n&&!FileIsEnding(h);i++){int no=(int)FileReadNumber(h);string pt=FileReadString(h),pa=FileReadString(h);int k=no-1;if(k>=0&&k<MA_BUILDER_MAX_UI_SLOTS){slot[k]=pt;params[k]=pa;}}FileClose(h);selected=-1;scroll=0;reason="LOADED: "+nm;return true;}
 void Show(){Delete();Box();Lab("TITLE",656,70,"EA LOGIC / FREE-SLOT BUILDER",10);Lab("SUB",656,92,"Definition: BUILDER_E01   Role: ENTRY   NO ORDERS",8);Lab("HELP",656,112,"ADD/EDIT -> EA PARTS -> configure -> APPLY.  + adds slots; list scrolls.",8);int y=145;Clamp();for(int r=0;r<MA_BUILDER_VISIBLE_ROWS;r++){int i=scroll+r;if(i>=slot_count)break;string no=(i<9?"0":"")+IntegerToString(i+1);Lab("N"+IntegerToString(r),656,y+4,(i==selected?"> ":"  ")+no,8);string shown=slot[i];if(params[i]!="")shown+="  {"+params[i]+"}";int st=(i==selected?2:(slot[i]!="EMPTY"?1:0));Btn("S"+IntegerToString(r),686,y,360,shown,st);Btn("E"+IntegerToString(r),1055,y,90,(slot[i]=="EMPTY"?"ADD":"EDIT"),st);y+=30;}Btn("UP",1155,145,45,"UP");Btn("DOWN",1155,175,45,"DOWN");Btn("PLUS",1208,145,45,"+");Btn("MINUS",1208,175,45,"-");Lab("RANGE",1155,210,IntegerToString(scroll+1)+"-"+IntegerToString(MathMin(slot_count,scroll+MA_BUILDER_VISIBLE_ROWS))+"/"+IntegerToString(slot_count),8);Lab("NL",656,397,"Name",8);Edit("NAME",700,393,180,"BUILDER_E01");Btn("SAVE",890,393,75,"SAVE");Btn("LOAD",975,393,75,"LOAD");Btn("CLEAR",1060,393,85,"CLEAR");Btn("EXAMPLE",1155,393,120,"O01 ENTRY");Lab("STATUS",656,423,"Ready",8);ChartRedraw();}
 void Status(string s,color c=clrWhite){Lab("STATUS",656,423,s,8);ObjectSetInteger(0,p+"STATUS",OBJPROP_COLOR,c);ChartRedraw();}
 void Hide(){int total=ObjectsTotal(0,0,-1);for(int i=total-1;i>=0;i--){string n=ObjectName(0,i,0,-1);if(StringFind(n,p)==0)ObjectSetInteger(0,n,OBJPROP_TIMEFRAMES,0);}ChartRedraw();}
 void Delete(){ObjectsDeleteAll(0,p);}
 int OnChartEvent(const int id,const long lparam,const double dparam,const string s){if(id==CHARTEVENT_MOUSE_WHEEL){if(dparam>0)scroll--;else scroll++;Clamp();Show();return 1;}if(id!=CHARTEVENT_OBJECT_CLICK)return 0;if(s==p+"UP"){scroll--;Clamp();Show();return 1;}if(s==p+"DOWN"){scroll++;Clamp();Show();return 1;}if(s==p+"PLUS"){if(slot_count<MA_BUILDER_MAX_UI_SLOTS){slot_count++;scroll=MathMax(0,slot_count-MA_BUILDER_VISIBLE_ROWS);Show();}return 1;}if(s==p+"MINUS"){if(slot_count<=MA_BUILDER_INITIAL_SLOTS){Show();Status("MINIMUM: 8 SLOTS",C'245,150,70');return 1;}int last=slot_count-1;if(slot[last]!="EMPTY"){Show();Status("LAST SLOT NOT EMPTY - DELETE IT FIRST",C'245,150,70');return 1;}slot_count--;if(selected>=slot_count)selected=-1;Clamp();Show();return 1;}if(s==p+"CLEAR"){ClearSlots();Show();return 1;}if(s==p+"EXAMPLE"){LoadO01EntryExample();Show();return 1;}if(s==p+"SAVE"){string w;if(SaveNamed(w)){Show();Status(w,C'70,210,150');}else{Show();Status(w,C'245,150,70');}return 3;}if(s==p+"LOAD"){string w;if(LoadNamed(w)){Show();Status(w,C'70,210,150');return 4;}Show();Status(w,C'245,150,70');return 3;}int r=Row(s);if(r>=0){int i=scroll+r;if(i<slot_count){selected=i;Show();return 2;}}return 0;}
};
#endif