//+------------------------------------------------------------------+
//| MultiAlpha_Builder_Parts_Picker_v1_09.mqh                       |
//| Role-scoped ENTRY/MANAGE/EXIT part picker. UI only / NO ORDERS.  |
//+------------------------------------------------------------------+
#ifndef MULTIALPHA_BUILDER_PARTS_PICKER_V1_09_MQH
#define MULTIALPHA_BUILDER_PARTS_PICKER_V1_09_MQH
class CMultiAlphaBuilderPartsPicker109{
 string p; int selected_slot,role; string chosen,loaded_params;
 void Lab(string id,int x,int y,string s,int fs=8){string n=p+id;if(ObjectFind(0,n)<0)ObjectCreate(0,n,OBJ_LABEL,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(0,n,OBJPROP_COLOR,clrWhite);ObjectSetInteger(0,n,OBJPROP_FONTSIZE,fs);ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false);ObjectSetInteger(0,n,OBJPROP_ZORDER,35);ObjectSetString(0,n,OBJPROP_TEXT,s);}
 void Btn(string id,int x,int y,int w,string s,bool active=false){string n=p+id;if(ObjectFind(0,n)<0)ObjectCreate(0,n,OBJ_BUTTON,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(0,n,OBJPROP_XSIZE,w);ObjectSetInteger(0,n,OBJPROP_YSIZE,24);ObjectSetInteger(0,n,OBJPROP_BGCOLOR,active?C'34,105,125':C'24,39,49');ObjectSetInteger(0,n,OBJPROP_COLOR,clrWhite);ObjectSetInteger(0,n,OBJPROP_FONTSIZE,8);ObjectSetInteger(0,n,OBJPROP_ZORDER,40);ObjectSetString(0,n,OBJPROP_TEXT,s);}
 void Edit(string id,int x,int y,int w,string s){string n=p+id;if(ObjectFind(0,n)<0)ObjectCreate(0,n,OBJ_EDIT,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(0,n,OBJPROP_XSIZE,w);ObjectSetInteger(0,n,OBJPROP_YSIZE,22);ObjectSetInteger(0,n,OBJPROP_BGCOLOR,C'20,31,40');ObjectSetInteger(0,n,OBJPROP_COLOR,clrWhite);ObjectSetInteger(0,n,OBJPROP_BORDER_COLOR,C'65,90,105');ObjectSetInteger(0,n,OBJPROP_FONTSIZE,8);ObjectSetInteger(0,n,OBJPROP_ZORDER,45);ObjectSetString(0,n,OBJPROP_TEXT,s);}
 void Box(){string n=p+"BG";if(ObjectFind(0,n)<0)ObjectCreate(0,n,OBJ_RECTANGLE_LABEL,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,640);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,58);ObjectSetInteger(0,n,OBJPROP_XSIZE,660);ObjectSetInteger(0,n,OBJPROP_YSIZE,430);ObjectSetInteger(0,n,OBJPROP_BGCOLOR,C'12,20,27');ObjectSetInteger(0,n,OBJPROP_BORDER_COLOR,C'55,70,80');ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false);ObjectSetInteger(0,n,OBJPROP_ZORDER,20);}
 string RN(){return role==0?"ENTRY":role==1?"MANAGE":"EXIT";} bool Active(string id){return chosen==id;} string Val(string key,string def){string a[];int n=StringSplit(loaded_params,';',a);for(int i=0;i<n;i++){int q=StringFind(a[i],"=");if(q>0&&StringSubstr(a[i],0,q)==key)return StringSubstr(a[i],q+1);}return def;} string Txt(string id,string def){string n=p+id;return ObjectFind(0,n)>=0?ObjectGetString(0,n,OBJPROP_TEXT):def;}
 void DrawParams(){int cy=(role==1?342:310),py=(role==1?368:336),ey=(role==1?364:332),ay=(role==1?446:406);Lab("CFG",656,cy,"PART SETTINGS",9);if(chosen=="RSI_THRESHOLD"){Lab("L1",656,py,"TF");Edit("P1",700,ey,80,Val("TF","CURRENT"));Lab("L2",790,py,"Period");Edit("P2",840,ey,60,Val("PERIOD","8"));Lab("L3",910,py,"Price");Edit("P3",955,ey,80,Val("PRICE","CLOSE"));Lab("L4",656,366,"Cond");Edit("P4",700,362,80,Val("COND","LT"));Lab("L5",790,366,"Level");Edit("P5",840,362,80,Val("LEVEL","30"));Lab("L6",930,366,"Upper");Edit("P6",975,362,70,Val("UPPER","70"));}else if(chosen=="MA"){Lab("L1",656,py,"TF");Edit("P1",700,ey,80,Val("TF","CURRENT"));Lab("L2",790,py,"Period");Edit("P2",840,ey,60,Val("PERIOD","20"));Lab("L3",910,py,"Method");Edit("P3",965,ey,80,Val("METHOD","SMA"));}else if(chosen=="ATR"){Lab("L1",656,py,"TF");Edit("P1",700,ey,80,Val("TF","CURRENT"));Lab("L2",790,py,"Period");Edit("P2",840,ey,60,Val("PERIOD","15"));Lab("L3",910,py,"Min");Edit("P3",950,ey,70,Val("MIN","0"));Lab("L4",1030,py,"Max");Edit("P4",1070,ey,80,Val("MAX","10000"));}else if(chosen=="FIXED_DISTANCE"){Lab("L1",656,py,"Points");Edit("P1",710,ey,90,Val("POINTS","200"));}
else if(chosen=="DYNAMIC_DISTANCE"){Lab("L1",656,py,"Start #");Edit("P1",710,ey,70,Val("START_ORDER","3"));Lab("L2",790,py,"Start pts");Edit("P2",850,ey,80,Val("START_POINTS","300"));Lab("L3",940,336,"Mult");Edit("P3",980,ey,80,Val("MULT","1.20"));}
else if(chosen=="MAX_LOT"){Lab("L1",656,py,"Max lot");Edit("P1",715,ey,90,Val("LOT","5.00"));}
else if(chosen=="MAX_TOTAL_LOT"){Lab("L1",656,py,"Max total");Edit("P1",725,ey,90,Val("LOT","1.20"));}
else if(chosen=="FIXED_TP"){Lab("L1",656,py,"Points");Edit("P1",710,ey,90,Val("POINTS","110"));}else if(chosen=="LOT_MULTIPLIER"){Lab("L1",656,py,"Multiplier");Edit("P1",725,ey,90,Val("MULT","1.50"));}else if(chosen=="MAX_ORDERS"){Lab("L1",656,py,"Orders");Edit("P1",710,ey,90,Val("COUNT","10"));}else if(chosen=="VIRTUAL_SL"){Lab("L1",656,py,"Points");Edit("P1",710,ey,90,Val("POINTS","1500"));}else if(chosen=="SINGLE_TRAILING"||chosen=="BASKET_TRAILING"){Lab("L1",656,py,"Start");Edit("P1",700,ey,70,Val("START",chosen=="SINGLE_TRAILING"?"110":"100"));Lab("L2",780,336,"Lock");Edit("P2",820,332,70,Val("LOCK",chosen=="SINGLE_TRAILING"?"60":"50"));Lab("L3",900,336,"Dist");Edit("P3",940,332,70,Val("DIST","50"));Lab("L4",1020,336,"Step");Edit("P4",1060,332,70,Val("STEP","10"));}else Lab("NOP",656,py,"This part has no editable numeric parameters.",8);Btn("APPLY",656,ay,120,"APPLY",true);Btn("CANCEL",786,ay,120,"CANCEL");Btn("DELETE",916,ay,120,"DELETE");}
 void CommonLogic(){int ly=(role==1?278:218),by=(role==1?298:238);Lab("LOG",656,ly,"LOGIC",9);Btn("AND",656,by,100,"AND",Active("AND"));Btn("OR",766,by,100,"OR",Active("OR"));}
public:
 CMultiAlphaBuilderPartsPicker109(){p="MAPICK109_";selected_slot=-1;role=0;chosen="";loaded_params="";} void SetRole(int r){role=MathMax(0,MathMin(2,r));} void SetSlot(int i,string part,string par){selected_slot=i;chosen=(part=="EMPTY"?"":part);loaded_params=par;} string Chosen(){return chosen==""?"EMPTY":chosen;}
 string Parameters(){if(chosen=="RSI_THRESHOLD")return "TF="+Txt("P1","CURRENT")+";PERIOD="+Txt("P2","8")+";PRICE="+Txt("P3","CLOSE")+";COND="+Txt("P4","LT")+";LEVEL="+Txt("P5","30")+";UPPER="+Txt("P6","70");if(chosen=="MA")return "TF="+Txt("P1","CURRENT")+";PERIOD="+Txt("P2","20")+";METHOD="+Txt("P3","SMA");if(chosen=="ATR")return "TF="+Txt("P1","CURRENT")+";PERIOD="+Txt("P2","15")+";MIN="+Txt("P3","0")+";MAX="+Txt("P4","10000");if(chosen=="FIXED_DISTANCE")return "POINTS="+Txt("P1","200");if(chosen=="DYNAMIC_DISTANCE")return "START_ORDER="+Txt("P1","3")+";START_POINTS="+Txt("P2","300")+";MULT="+Txt("P3","1.20");if(chosen=="MAX_LOT")return "LOT="+Txt("P1","5.00");if(chosen=="MAX_TOTAL_LOT")return "LOT="+Txt("P1","1.20");if(chosen=="FIXED_TP")return "POINTS="+Txt("P1","110");if(chosen=="LOT_MULTIPLIER")return "MULT="+Txt("P1","1.50");if(chosen=="MAX_ORDERS")return "COUNT="+Txt("P1","10");if(chosen=="VIRTUAL_SL")return "POINTS="+Txt("P1","1500");if(chosen=="SINGLE_TRAILING"||chosen=="BASKET_TRAILING")return "START="+Txt("P1",chosen=="SINGLE_TRAILING"?"110":"100")+";LOCK="+Txt("P2",chosen=="SINGLE_TRAILING"?"60":"50")+";DIST="+Txt("P3","50")+";STEP="+Txt("P4","10");return "";}
 void Show(){Delete();Box();Lab("TITLE",656,70,"EA PARTS / "+RN()+" BUILDER",10);Lab("SEL",656,94,"Target slot: "+(selected_slot>=0?IntegerToString(selected_slot+1):"NONE")+"   Active: "+(chosen==""?"NONE":chosen),8);if(role==0){Lab("CAT",656,122,"ENTRY PARTS",9);Btn("RSI",656,142,105,"RSI",Active("RSI_THRESHOLD"));Btn("MA",771,142,105,"MA",Active("MA"));Btn("ATR",886,142,105,"ATR",Active("ATR"));Btn("TIME",1001,142,105,"TIME",Active("TIME_ALLOWED"));Btn("FILTERS",1116,142,105,"FILTERS",Active("FILTERS_OK"));Btn("BUY",656,178,105,"BUY",Active("BUY"));Btn("SELL",771,178,105,"SELL",Active("SELL"));Btn("COUNT",886,178,120,"SIDE COUNT",Active("SIDE_COUNT_ZERO"));}else if(role==1){Lab("CAT",656,122,"MANAGE PARTS",9);Btn("COUNT",656,142,115,"SIDE COUNT",Active("SIDE_COUNT"));Btn("AVG",781,142,115,"AVG PRICE",Active("AVG_PRICE"));Btn("LAST",906,142,115,"LAST PRICE",Active("LAST_PRICE"));Btn("DIST",1031,142,130,"FIXED DIST",Active("FIXED_DISTANCE"));Btn("DYN",656,178,130,"DYNAMIC DIST",Active("DYNAMIC_DISTANCE"));Btn("MULT",796,178,120,"LOT MULT",Active("LOT_MULTIPLIER"));Btn("MAXLOT",926,178,105,"MAX LOT",Active("MAX_LOT"));Btn("MAXTOT",1041,178,120,"MAX TOTAL",Active("MAX_TOTAL_LOT"));Btn("MAXORD",656,202,120,"MAX ORDERS",Active("MAX_ORDERS"));Btn("BAR",786,202,120,"ONE/BAR",Active("ONE_ORDER_PER_BAR"));Btn("TIME",916,202,105,"TIME",Active("TIME_ALLOWED"));Btn("NEWS",1031,202,105,"NEWS",Active("NEWS_CLEAR"));Btn("SPREAD",656,226,115,"SPREAD",Active("SPREAD_OK"));Btn("TRPAUSE",781,226,135,"TRAIL PAUSE",Active("TRAILING_PAUSE"));Btn("ADDB",926,226,105,"ADD BUY",Active("ADD_BUY"));Btn("ADDS",1041,226,105,"ADD SELL",Active("ADD_SELL"));}else{Lab("CAT",656,122,"EXIT PARTS",9);Btn("AVG",656,142,115,"AVG PRICE",Active("AVG_PRICE"));Btn("MOVE",781,142,115,"MOVE PTS",Active("MOVE_POINTS"));Btn("COUNT",906,142,115,"SIDE COUNT",Active("SIDE_COUNT"));Btn("VSL",1031,142,115,"VIRTUAL SL",Active("VIRTUAL_SL"));Btn("FTP",1156,142,105,"FIXED TP",Active("FIXED_TP"));Btn("STR",656,178,130,"SINGLE TRAIL",Active("SINGLE_TRAILING"));Btn("BTR",796,178,130,"BASKET TRAIL",Active("BASKET_TRAILING"));Btn("CLOSE",936,178,115,"CLOSE",Active("CLOSE_SIDE"));}CommonLogic();Btn("EMPTY",876,(role==1?298:238),100,"EMPTY",Active("EMPTY"));DrawParams();ChartRedraw();}
 void Hide(){int total=ObjectsTotal(0,0,-1);for(int i=total-1;i>=0;i--){string n=ObjectName(0,i,0,-1);if(StringFind(n,p)==0)ObjectSetInteger(0,n,OBJPROP_TIMEFRAMES,0);}ChartRedraw();} void Delete(){ObjectsDeleteAll(0,p);}
 int OnChartEvent(const int id,const string s){if(id!=CHARTEVENT_OBJECT_CLICK)return 0;string next="";if(s==p+"RSI")next="RSI_THRESHOLD";else if(s==p+"MA")next="MA";else if(s==p+"ATR")next="ATR";else if(s==p+"TIME")next="TIME_ALLOWED";else if(s==p+"FILTERS")next="FILTERS_OK";else if(s==p+"COUNT")next=(role==0?"SIDE_COUNT_ZERO":"SIDE_COUNT");else if(s==p+"BUY")next="BUY";else if(s==p+"SELL")next="SELL";else if(s==p+"AVG")next="AVG_PRICE";else if(s==p+"LAST")next="LAST_PRICE";else if(s==p+"DIST")next="FIXED_DISTANCE";else if(s==p+"DYN")next="DYNAMIC_DISTANCE";else if(s==p+"MAXLOT")next="MAX_LOT";else if(s==p+"MAXTOT")next="MAX_TOTAL_LOT";else if(s==p+"BAR")next="ONE_ORDER_PER_BAR";else if(s==p+"TIME")next="TIME_ALLOWED";else if(s==p+"NEWS")next="NEWS_CLEAR";else if(s==p+"SPREAD")next="SPREAD_OK";else if(s==p+"TRPAUSE")next="TRAILING_PAUSE";else if(s==p+"MULT")next="LOT_MULTIPLIER";else if(s==p+"MAXORD")next="MAX_ORDERS";else if(s==p+"ADDB")next="ADD_BUY";else if(s==p+"ADDS")next="ADD_SELL";else if(s==p+"MOVE")next="MOVE_POINTS";else if(s==p+"VSL")next="VIRTUAL_SL";else if(s==p+"FTP")next="FIXED_TP";else if(s==p+"STR")next="SINGLE_TRAILING";else if(s==p+"BTR")next="BASKET_TRAILING";else if(s==p+"CLOSE")next="CLOSE_SIDE";else if(s==p+"AND")next="AND";else if(s==p+"OR")next="OR";else if(s==p+"EMPTY")next="EMPTY";else if(s==p+"APPLY")return 2;else if(s==p+"CANCEL")return 3;else if(s==p+"DELETE")return 4;else return 0;if(next!=chosen){chosen=next;loaded_params="";}Show();return 1;}
};
#endif
